thread 'main' panicked at 'assertion failed: r.is_err()', ui/iterators/iter-step-overflow-debug.rs:13:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
