thread 'main' panicked at 'try to catch me', ui/panic-runtime/lto-abort.rs:28:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: s.unwrap().code() != Some(0)', ui/panic-runtime/lto-abort.rs:32:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
