// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn produce() -> Result<&str, T> {
    let mut _0: std::result::Result<&str, T>;
    let _1: &str;

    bb0: {
        _1 = const "22";
        _0 = Result::<&str, T>::Ok(_1);
        return;
    }
}

fn main() -> () {
    let mut _0: ();
    let _1: usize;
    let mut _2: std::result::Result<usize, std::num::ParseIntError>;
    let mut _3: std::result::Result<&str, std::num::ParseIntError>;
    let _4: ();
    let mut _5: std::fmt::Arguments<'_>;
    let mut _6: &[&str];
    let _7: &[&str; 2];
    let _8: [&str; 2];
    let mut _9: &[core::fmt::rt::Argument<'_>];
    let _10: &[core::fmt::rt::Argument<'_>; 1];
    let _11: [core::fmt::rt::Argument<'_>; 1];
    let mut _12: core::fmt::rt::Argument<'_>;
    let _13: &usize;
    scope 1 {
        debug x => _1;
    }

    bb0: {
        _3 = produce::<ParseIntError>() -> bb1;
    }

    bb1: {
        _2 = Result::<&str, ParseIntError>::and_then::<usize, [closure@ui/diverging-fallback-method-chain.rs:17:19: 17:22]>(move _3, const ZeroSized: [closure@ui/diverging-fallback-method-chain.rs:17:19: 17:22]) -> bb2;
    }

    bb2: {
        _1 = Result::<usize, ParseIntError>::unwrap_or_else::<[closure@ui/diverging-fallback-method-chain.rs:18:25: 18:28]>(move _2, const ZeroSized: [closure@ui/diverging-fallback-method-chain.rs:18:25: 18:28]) -> bb3;
    }

    bb3: {
        _8 = [const "", const "\n"];
        _7 = &_8;
        _6 = _7 as &[&str] (Pointer(Unsize));
        _13 = &_1;
        _12 = core::fmt::rt::Argument::<'_>::new_display::<usize>(_13) -> bb4;
    }

    bb4: {
        _11 = [move _12];
        _10 = &_11;
        _9 = _10 as &[core::fmt::rt::Argument<'_>] (Pointer(Unsize));
        _5 = Arguments::<'_>::new_v1(move _6, move _9) -> bb5;
    }

    bb5: {
        _4 = _print(move _5) -> bb6;
    }

    bb6: {
        return;
    }
}

fn main::{closure#0}(_1: [closure@ui/diverging-fallback-method-chain.rs:17:19: 17:22], _2: &str) -> Result<usize, ParseIntError> {
    debug x => _2;
    let mut _0: std::result::Result<usize, std::num::ParseIntError>;

    bb0: {
        _0 = core::str::<impl str>::parse::<usize>(_2) -> bb1;
    }

    bb1: {
        return;
    }
}

fn main::{closure#1}(_1: [closure@ui/diverging-fallback-method-chain.rs:18:25: 18:28], _2: ParseIntError) -> usize {
    let mut _0: usize;
    let mut _3: !;

    bb0: {
        _3 = begin_panic::<&str>(const "explicit panic");
    }
}
