// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> () {
    let mut _0: ();
    let mut _1: (&std::result::Result<i32, std::num::ParseIntError>, &std::result::Result<i32, std::num::ParseIntError>);
    let mut _2: &std::result::Result<i32, std::num::ParseIntError>;
    let _3: std::result::Result<i32, std::num::ParseIntError>;
    let mut _4: &std::result::Result<i32, std::num::ParseIntError>;
    let _5: std::result::Result<i32, std::num::ParseIntError>;
    let _6: &std::result::Result<i32, std::num::ParseIntError>;
    let _7: &std::result::Result<i32, std::num::ParseIntError>;
    let mut _8: bool;
    let mut _9: bool;
    let _11: !;
    let mut _12: std::option::Option<std::fmt::Arguments<'_>>;
    scope 1 {
        debug left_val => _6;
        debug right_val => _7;
        let _10: core::panicking::AssertKind;
        scope 2 {
            debug kind => _10;
        }
    }

    bb0: {
        _3 = parse() -> bb1;
    }

    bb1: {
        _2 = &_3;
        _5 = Result::<i32, ParseIntError>::Ok(const 1_i32);
        _4 = &_5;
        _1 = (move _2, move _4);
        _6 = (_1.0: &std::result::Result<i32, std::num::ParseIntError>);
        _7 = (_1.1: &std::result::Result<i32, std::num::ParseIntError>);
        _9 = <Result<i32, ParseIntError> as PartialEq>::eq(_6, _7) -> bb2;
    }

    bb2: {
        _8 = Not(move _9);
        switchInt(move _8) -> [0: bb4, otherwise: bb3];
    }

    bb3: {
        _10 = core::panicking::AssertKind::Eq;
        _12 = Option::<Arguments<'_>>::None;
        _11 = core::panicking::assert_failed::<Result<i32, ParseIntError>, Result<i32, ParseIntError>>(move _10, _6, _7, move _12);
    }

    bb4: {
        return;
    }
}

fn parse() -> Result<i32, ParseIntError> {
    let mut _0: std::result::Result<i32, std::num::ParseIntError>;
    let mut _1: std::ops::ControlFlow<std::result::Result<std::convert::Infallible, std::num::ParseIntError>, i32>;
    let mut _2: std::result::Result<i32, std::num::ParseIntError>;
    let _3: &str;
    let mut _4: isize;
    let _5: std::result::Result<std::convert::Infallible, std::num::ParseIntError>;
    let _6: i32;
    scope 1 {
        debug residual => _5;
        scope 2 {
        }
    }
    scope 3 {
        debug val => _6;
        scope 4 {
        }
    }

    bb0: {
        _3 = const "1";
        _2 = core::str::<impl str>::parse::<i32>(_3) -> bb1;
    }

    bb1: {
        _1 = <Result<i32, ParseIntError> as Try>::branch(move _2) -> bb2;
    }

    bb2: {
        _4 = discriminant(_1);
        switchInt(move _4) -> [0: bb3, 1: bb5, otherwise: bb4];
    }

    bb3: {
        _6 = ((_1 as Continue).0: i32);
        _0 = Result::<i32, ParseIntError>::Ok(_6);
        goto -> bb6;
    }

    bb4: {
        unreachable;
    }

    bb5: {
        _5 = move ((_1 as Break).0: std::result::Result<std::convert::Infallible, std::num::ParseIntError>);
        _0 = <Result<i32, ParseIntError> as FromResidual<Result<Infallible, ParseIntError>>>::from_residual(move _5) -> bb6;
    }

    bb6: {
        return;
    }
}

const val: char = {
    let mut _0: char;

    bb0: {
        _0 = const 'a';
        return;
    }
}

const err: char = {
    let mut _0: char;

    bb0: {
        _0 = const 'b';
        return;
    }
}
